"""Single-source defaults for backend IPC runtime knobs."""

from __future__ import annotations

from pathlib import Path

IPC_DEFAULT_TCP_HOST = "127.0.0.1"
IPC_DEFAULT_TCP_PORT = 54321
IPC_DEFAULT_MAX_FRAME_BYTES = 65536
IPC_DEFAULT_REQUEST_TIMEOUT_MS = 10000
IPC_DEFAULT_HEARTBEAT_INTERVAL_MS = 3000
IPC_DEFAULT_HEARTBEAT_MISS_THRESHOLD = 2
IPC_DEFAULT_DATA_DIR_NAME = ".flow_engine"
IPC_DEFAULT_SOCKET_NAME = "daemon.sock"
IPC_DEFAULT_PID_NAME = "daemon.pid"
IPC_DEFAULT_SOCKET_PATH = Path.home() / IPC_DEFAULT_DATA_DIR_NAME / IPC_DEFAULT_SOCKET_NAME

# Local safety bound before hello succeeds.
IPC_DEFAULT_PRE_HANDSHAKE_MAX_FRAME_BYTES = IPC_DEFAULT_MAX_FRAME_BYTES
