from __future__ import annotations

CANVAS_GRID_MARGINS = (0, 0, 0, 0)
CANVAS_GRID_HORIZONTAL_SPACING = 8
CANVAS_GRID_VERTICAL_SPACING = 8
CANVAS_SLOT_LAYOUT_MARGINS = (0, 0, 0, 0)
CANVAS_SLOT_LAYOUT_SPACING = 6

