"""Flow IPC V2 constants."""

from __future__ import annotations

PROTOCOL_VERSION = 2

TYPE_REQUEST = "request"
TYPE_RESPONSE = "response"
TYPE_PUSH = "push"

ROLE_RPC = "rpc"
ROLE_PUSH = "push"
ROLE_DUPLEX = "duplex"

TRANSPORT_UNIX = "unix"
TRANSPORT_TCP = "tcp"

METHOD_SESSION_HELLO = "session.hello"
METHOD_SESSION_PING = "session.ping"
METHOD_SESSION_BYE = "session.bye"

EVENT_SESSION_KEEPALIVE = "session.keepalive"
EVENT_SESSION_CLOSING = "session.closing"

ERR_UNSUPPORTED_PROTOCOL = "ERR_UNSUPPORTED_PROTOCOL"
ERR_INVALID_FRAME = "ERR_INVALID_FRAME"
ERR_METHOD_NOT_FOUND = "ERR_METHOD_NOT_FOUND"
ERR_INVALID_PARAMS = "ERR_INVALID_PARAMS"
ERR_CAPABILITY_REQUIRED = "ERR_CAPABILITY_REQUIRED"
ERR_ROLE_MISMATCH = "ERR_ROLE_MISMATCH"
ERR_REQUEST_TIMEOUT = "ERR_REQUEST_TIMEOUT"
ERR_DAEMON_OFFLINE = "ERR_DAEMON_OFFLINE"
ERR_DAEMON_SHUTTING_DOWN = "ERR_DAEMON_SHUTTING_DOWN"
ERR_INTERNAL = "ERR_INTERNAL"

RESERVED_ERROR_CODES = {
    ERR_UNSUPPORTED_PROTOCOL,
    ERR_INVALID_FRAME,
    ERR_METHOD_NOT_FOUND,
    ERR_INVALID_PARAMS,
    ERR_CAPABILITY_REQUIRED,
    ERR_ROLE_MISMATCH,
    ERR_REQUEST_TIMEOUT,
    ERR_DAEMON_OFFLINE,
    ERR_DAEMON_SHUTTING_DOWN,
    ERR_INTERNAL,
}
